---
title: "satRday challenge"
author: "Agoston Torok & Fanni Kling"
date: '2016 augusztus 18 '
output: html_document
---

```{r setup, include=FALSE}
#install.packages(pkgs="gdata")
options(java.parameters = "-Xmx4000m")
library(xlsx)

df <- read.xlsx2("BUD flights 2007-2012.xlsx", sheetIndex = 1,
                 colClasses = c(rep("character", 7),
                                "Date",
                                "numeric",
                                rep("character", 3),
                                rep("numeric", 4)))
```

## Map Creation

https://blog.dominodatalab.com/geographic-visualization-with-rs-ggmaps/
https://www.r-bloggers.com/r-beginners-plotting-locations-on-to-a-world-map/

```{r}
if (!"maps" %in% installed.packages()) install.packages("maps")
library("maps")

destinationCountries <- unique(as.character(df$COUNTRY))
ll.visited <- geocode(destinationCountries)
visit.x <- ll.visited$lon
visit.y <- ll.visited$lat
```

http://stackoverflow.com/a/27901570/5360901

```{r cars}
if (!"sp" %in% installed.packages()) install.packages("sp")
library("sp")
if (!"maps" %in% installed.packages()) install.packages("maps")
library("maps")
if (!"rgdal" %in% installed.packages()) install.packages("rgdal")
library("rgdal")
if (!"rgeos" %in% installed.packages()) install.packages("rgeos")
library("rgeos")

world <- readOGR("ne_50m_admin_0_countries.geojson", "OGRGeoJSON")
outline <- bbox(world)
outline <- data.frame(xmin=outline["x","min"],
                      xmax=outline["x","max"],
                      ymin=outline["y","min"],
                      ymax=outline["y","max"])

world <- fortify(world)

points <- data.frame(lon=c(-98.35, 134.21), lat=c(39.5, -25.36))

gg <- ggplot()
gg <- gg + geom_rect(data=outline, 
                     aes(xmin=xmin, xmax=xmax, ymin=ymin, ymax=ymax), 
                     color=1, fill="lightblue", size=0.3)
gg <- gg + geom_map(data=world, map=world,
                    aes(x=long, y=lat, map_id=id), 
                    fill="darkseagreen", color="gray10", size=0.3)
gg <- gg + geom_point(aes(x = visit.x, y = visit.y) ,color = "blue", size = 3)
gg <- gg + labs(x=NULL, y=NULL)
gg <- gg + coord_map("mollweide")
gg <- gg + theme_bw()
gg <- gg + theme(panel.grid=element_blank())
gg <- gg + theme(panel.border=element_blank())
gg <- gg + theme(axis.ticks=element_blank())
gg <- gg + theme(axis.text=element_blank())
gg

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
